name: "Publish and Deploy to Github Pages"

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: pages
          baseHref: /sliding-scene/